var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/annotate/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__4dcecaf0._.js")
R.c("server/chunks/ssr/node_modules_05136449._.js")
R.c("server/chunks/ssr/node_modules_next_dist_ed0865a8._.js")
R.c("server/chunks/ssr/src_app_ca777385._.js")
R.c("server/chunks/ssr/[root-of-the-server]__9a619a34._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__0cfb2850._.js")
R.c("server/chunks/ssr/_a2985d5b._.js")
R.c("server/chunks/ssr/_25f32361._.js")
R.m(88528)
R.m(11413)
module.exports=R.m(11413).exports
